In [1]:
import json as js
import pandas as pd
import numpy as np

In [ ]:
bus = pd.read_json('./yelp_academic_dataset_business.json', lines=True)
bus = bus.dropna()

In [86]:
discard = list()
states = ['IL', 'AZ', 'OH', 'PA', 'NV', 'NC', 'SC', 'WI',
       'TX', 'CO', 'NY', 'FL', 'VT', 'HI', 'OR', 'WA', 'CA',
       'VA', 'NE']
for i in bus.index:
    if 'Restaurants' not in bus.loc[i].categories or bus.loc[i].is_open == 0 or bus.loc[i].state not in states:
        #print(bus.loc[i].categories)
        discard.append(i)
        
bus.drop(discard, inplace=True)
bus.drop('is_open', axis=1, inplace=True)

In [88]:
f = open ('./Yelp_dataset_business_clean.json', 'w')

bus.to_json(path_or_buf=f)
f.close()

In [89]:
checkin = pd.read_json('./yelp_academic_dataset_checkin.json', lines=True, encoding='utf8')

In [90]:
busId = np.array(bus['business_id'])
#discard = list()
# for i in checkin.index:
#     if checkin.loc[i].business_id not in busId:
# #         print(checkin.loc[i].business_id)
#         if (i % 1000 == 0):
#             print(i)
#         discard.append(i)

#checkin.drop(discard, inplace=True)
checkin = checkin[checkin.business_id.isin(busId)]

In [92]:
f = open ('./Yelp_dataset_checkin_clean.json', 'w')

checkin.to_json(path_or_buf=f)
f.close()

In [2]:
test = pd.read_json('./Yelp_dataset_review_clean.json', encoding='utf8')
test

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
100001,75yxPqw3eBNmYX9WIWAabw,4PFwh5zbgyPhTGRtxkSZZA,-_yEVC3_3M6YOsamYfNFEw,5,0,0,0,I have not yet been in but the customer servic...,2013-09-09 20:21:11
100004,oLTbxfDMNf4gLkGIpv4xbA,dvwFC5u09dbG_16AeNKBmQ,zzSYBWuv_fXGtSgsO-6_1g,4,1,0,0,My daughters and I enjoyed our dining experien...,2012-07-21 01:49:04
100011,AK6twEVICwhbyuVTRRGxWw,Z6-ZsBP3DqfQNt2Xju6epA,Ks7EuyQVI2JEif4Xp70MmA,3,4,0,1,This is average Chinese food; fast and efficie...,2013-12-10 00:56:41
100014,Iu4KakD8tmAlorS8CAQiVg,9tfqpOnyIZ_Qw8inEMti8A,gwd1W_0Mgzqo3QxgXrt16Q,4,0,0,0,Great food. Service is slow at best. Great p...,2016-07-05 14:18:18
100017,ztBiRt4IDVlhZlgoInFe5Q,wTpbvjW4IUu8vboqkRbhsQ,v0FdDAXvEYieRWcngbCe1Q,5,0,0,0,"Chipotles is one of my favorites, but this pla...",2017-09-01 18:17:06
...,...,...,...,...,...,...,...,...,...
8021109,SkiPC10TBymnU-y8ScdQ_w,23cjtl3AWJtxKL3O78-Djw,e6ls6aHFa75xKEZUQUu1QQ,4,0,0,0,Tasty ramen with sushi options as well. The ch...,2019-12-08 00:49:06
8021118,gMDU14Fa_DVIcPvsKtubJA,_g6P8H3-qfbz1FxbffS68g,IsoLzudHC50oJLiEWpwV-w,3,1,3,1,Solid American food with a southern comfort fl...,2019-12-10 04:15:00
8021119,EcY_p50zPIQ2R6rf6-5CjA,Scmyz7MK4TbXXYcaLZxIxQ,kDCyqlYcstqnoqnfBRS5Og,5,15,6,13,I'm honestly not sure how I have never been to...,2019-06-06 15:01:53
8021120,-z_MM0pAf9RtZbyPlphTlA,lBuAACBEThaQHQGMzAlKpg,VKVDDHKtsdrnigeIf9S8RA,3,2,0,0,Food was decent but I will say the service too...,2018-07-05 18:45:21
8021121,nK0JGgr8aO4mcFPU4pDOEA,fiA6ztHPONUkmX6yKIXyHg,2SbyRgHWuWNlq18eHAx95Q,5,2,0,2,"Oh yeah! Not only that the service was good, t...",2019-12-07 00:29:55

In [121]:
reviewReader = pd.read_json('./yelp_academic_dataset_review.json', lines=True, encoding='utf8', chunksize=100000)

In [123]:
reviewDfList = list()
for chunk in reviewReader:
    userDfList.append(chunk[chunk.business_id.isin(busId)])

review = pd.concat(userDfList)

In [128]:
f = open ('./Yelp_dataset_review_clean.json', 'w')
review.to_json(path_or_buf=f)
f.close()